### ISSUE TITLE
remove the UI check for SO_0002165

### ISSUE THREAD

**Issue by emepyc** [opentargets/webapp#227]
The api was not giving a label for that functional consequence. Once it is fixed at the data / api level we should remove this check from the webapp.

**Comment by LucaFumis** [comment]
Has this been fixed already?
Searching the code for "SO_0002165" only points to the static variants.html page)

**Comment by emepyc** [comment]
Yes, I think this is fixed and the hack removed. To be sure, ask @ckongEbi to revise and close  https://github.com/opentargets/data_pipeline/issues/223

**Comment by ckongEbi** [comment]
What is the rest call for this? to check that this has been fixed from the backend.

**Comment by LucaFumis** [comment]
Thank you @emepyc - just had a look through this with @ckongEbi. 
The hack is still in place and the label still missing. Not a problem though.

Few info to find this quickly next time:

This affects *rare diseases* table in genetic associations on the evidence page:
http://www.targetvalidation.org/evidence/ENSG00000197386/Orphanet_399

Look in `src/components/rare-disease-table/rare-disease-table-directive.js`for 'SO 0002165' (without the underscore - I missed that yesterday)

**Comment by LucaFumis** [comment]
FYI this issue is still outstanding.
